databases:
  - name: skindisease
    databaseName: skindisease
    user: skindisease

services:
  - type: web
    name: skin-disease-detection
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn SkinDisease.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skindisease
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"